CREATE TABLE TEACHER(
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  age INTEGER(3) NOT NULL, --NUMBER(3) MEANS INTEGER
  notionality VARCHAR(2) NOT NULL,
  membership VARCHAR(1) NOT NULL,  
  PRIMARY KEY(id),
  FOREIGN KEY(nationality) REFERENCES NATIONALITY(COUNTRY_CODE),
  FOREIGN KEY(membership) REFERENCES MEMBERSHIP(MEMBERSHIP_CODE),

)

